repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        language_version: python3
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]

      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        require_serial: true

      - id: bandit
        name: bandit
        entry: bandit
        language: python
        language_version: python3
        types: [python]

      - id: safety
        name: safety
        entry: safety
        args: [check, --full-report]
        language: system
        files: requirements-dev requirements-airflow

      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: python
        language_version: python3
        types_or: [cython, pyi, python]
        args: ["--filter-files"]
        minimum_pre_commit_version: "2.9.0"
