version: '3.8'

x-airflow-common:
  &airflow-common
  env_file:
    - .env
  build:
    context: .
    args:
      - IMAGE=${AIRFLOW_IMAGE}
      - USER=${_AIRFLOW_WWW_USER_USERNAME}
  volumes:
    - ./${AIRFLOW_DAGS_DIRECTORY}:/opt/airflow/dags
    - ./${AIRFLOW_PLUGINS_DIRECTORY}:/opt/airflow/plugins
    - ./${AIRFLOW_LOGS_DIRECTORY}:/opt/airflow/logs
  user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
  depends_on:
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

services:
  postgres:
    image: ${POSTGRES_IMAGE}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '--port', '${POSTGRES_PORT}', '--username', '${POSTGRES_USER}']
      interval: 5s
      retries: 5
    restart: always

  redis:
    image: ${REDIS_IMAGE}
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - ${AIRFLOW_PORT}:${AIRFLOW_PORT}
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:8080/health']
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    restart: always

  airflow-init:
    <<: *airflow-common
    command: version

  flower:
    <<: *airflow-common
    command: celery flower
    ports:
      - ${FLOWER_PORT}:${FLOWER_PORT}
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:${FLOWER_PORT}/']
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      - airflow-worker

volumes:
  postgres-data:
